// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StageProject_RaceCore.Models;

#nullable disable

namespace StageProject_RaceCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427114144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StageProject_RaceCore.Models.Cyclist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Cyclists");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.DraftTurn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CyclistId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaceId", "TurnNumber")
                        .IsUnique();

                    b.ToTable("DraftTurns");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Jersey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.HasIndex("StageId");

                    b.ToTable("Jerseys");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PositionInDraft")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.PlayerPoints", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaceId");

                    b.HasIndex("StageId");

                    b.ToTable("PlayerPoints");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.PlayerSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.HasIndex("RaceId");

                    b.HasIndex("PlayerId", "RaceId", "CyclistId")
                        .IsUnique();

                    b.ToTable("PlayerSelections");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.PointsRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FromPosition")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("ToPosition")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PointsRules");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Year")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.RaceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.HasIndex("TeamId");

                    b.HasIndex("RaceId", "CyclistId")
                        .IsUnique();

                    b.ToTable("RaceEntries");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId", "StageNumber")
                        .IsUnique();

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.StageResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.HasIndex("StageId", "CyclistId")
                        .IsUnique();

                    b.ToTable("StageResults");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Tag");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Cyclist", b =>
                {
                    b.HasOne("StageProject_RaceCore.Models.Team", "Team")
                        .WithMany("Cyclists")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.DraftTurn", b =>
                {
                    b.HasOne("StageProject_RaceCore.Models.Cyclist", "Cyclist")
                        .WithMany("DraftTurns")
                        .HasForeignKey("CyclistId");

                    b.HasOne("StageProject_RaceCore.Models.Player", "Player")
                        .WithMany("DraftTurns")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Race", "Race")
                        .WithMany("DraftTurns")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cyclist");

                    b.Navigation("Player");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Jersey", b =>
                {
                    b.HasOne("StageProject_RaceCore.Models.Cyclist", "Cyclist")
                        .WithMany("Jerseys")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Stage", "Stage")
                        .WithMany("Jerseys")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cyclist");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.PlayerPoints", b =>
                {
                    b.HasOne("StageProject_RaceCore.Models.Cyclist", "Cyclist")
                        .WithMany("PlayerPoints")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Player", "Player")
                        .WithMany("PlayerPoints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Stage", "Stage")
                        .WithMany("PlayerPoints")
                        .HasForeignKey("StageId");

                    b.Navigation("Cyclist");

                    b.Navigation("Player");

                    b.Navigation("Race");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.PlayerSelection", b =>
                {
                    b.HasOne("StageProject_RaceCore.Models.Cyclist", "Cyclist")
                        .WithMany("PlayerSelections")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Player", "Player")
                        .WithMany("Selections")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Race", "Race")
                        .WithMany("PlayerSelections")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cyclist");

                    b.Navigation("Player");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.RaceEntry", b =>
                {
                    b.HasOne("StageProject_RaceCore.Models.Cyclist", "Cyclist")
                        .WithMany("RaceEntries")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Race", "Race")
                        .WithMany("RaceEntries")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Team", "Team")
                        .WithMany("RaceEntries")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cyclist");

                    b.Navigation("Race");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Stage", b =>
                {
                    b.HasOne("StageProject_RaceCore.Models.Race", "Race")
                        .WithMany("Stages")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.StageResult", b =>
                {
                    b.HasOne("StageProject_RaceCore.Models.Cyclist", "Cyclist")
                        .WithMany("StageResults")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageProject_RaceCore.Models.Stage", "Stage")
                        .WithMany("Results")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cyclist");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Cyclist", b =>
                {
                    b.Navigation("DraftTurns");

                    b.Navigation("Jerseys");

                    b.Navigation("PlayerPoints");

                    b.Navigation("PlayerSelections");

                    b.Navigation("RaceEntries");

                    b.Navigation("StageResults");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Player", b =>
                {
                    b.Navigation("DraftTurns");

                    b.Navigation("PlayerPoints");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Race", b =>
                {
                    b.Navigation("DraftTurns");

                    b.Navigation("PlayerSelections");

                    b.Navigation("RaceEntries");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Stage", b =>
                {
                    b.Navigation("Jerseys");

                    b.Navigation("PlayerPoints");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("StageProject_RaceCore.Models.Team", b =>
                {
                    b.Navigation("Cyclists");

                    b.Navigation("RaceEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
